### ISSUE TITLE
provide documents on the website

### ISSUE THREAD

**Issue by codingJJJ** [huozhi/bunchee#132]
provide documents on the website,for example quick start and API infomation, options config infomation.

**Comment by huozhi** [comment]
Hi, thanks for the feedback. I'm not sure how long will it take or if it's worthy effort to make a website for it. Most content are grouped in readme for now. 

What do you feel if is missing the most for the readme? Like description for the config options?
Since it's mostly a CLI tool, so you can directly start to use it as the **Usage** section mentioned.

**Comment by codingJJJ** [comment]
I think the nodejs API options is too simple,i'm not get more infomation  without source code，I hope  provider more demos about options，but it's my personal suggestion for reference.

**Comment by huozhi** [comment]
Ah I see, will extend the description for API later indeed!

Would you mind sharing what stuff you're building on top of the bunchee node API rather than using it as CLI?

**Comment by codingJJJ** [comment]
yeah，i wana use API with node.js code,but I can't get options infomation from the readme

**Comment by huozhi** [comment]
I updated the readme with available options now, let me know if there's anything else you need from it 🙏
